version: '3.6'
services:
  keylime-verifier:
    build:
      context: ./docker/fedora/
      dockerfile: keylime_py.Dockerfile
    image: keylime_py
    #environment:
      #KEYLIME_VERIFIER_ENABLE_AGENT_MTLS: false
      #KEYLIME_TENANT_ENABLE_AGENT_MTLS: false
      #KEYLIME_AGENT_ENABLE_INSECURE_PAYLOAD: true
    hostname: 'keylime-verifier'
    volumes:
      - keylime-volume:/var/lib/keylime
      - swtpm-volume:/var/lib/swtpm-localca
    network_mode: host
    ports:
        - "8892:8892" # verifier revocation port
        - "8881:8881" # verifier listen port
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/keylime_verifier || \
        sleep 100000

  keylime-registrar:
    build:
      context: ./docker/fedora/
      dockerfile: keylime_py.Dockerfile
    image: keylime_py
    hostname: 'keylime-registrar'
    volumes:
      - keylime-volume:/var/lib/keylime
      - swtpm-volume:/var/lib/swtpm-localca
    network_mode: host
    ports:
        - "8891:8891" # registrar TLS listen port
        - "8890:8890" # registrar listen port
    command: ["/root/wait.sh", "/var/lib/keylime/cv_ca/client-cert.crt", "keylime_registrar"]

  keylime-agent:
    build:
      context: ./docker/fedora/
      dockerfile: keylime_rust.Dockerfile
    privileged: true # for mounting tmpfs
    image: keylime_rust
    hostname: 'keylime-agent'
    network_mode: host
    #environment:
      #KEYLIME_AGENT_ENABLE_AGENT_MTLS: false
      #KEYLIME_AGENT_ENABLE_INSECURE_PAYLOAD: true
    environment:
      TCTI: tabrmd:bus_type=system
    volumes:
      - keylime-volume:/var/lib/keylime
      - swtpm-volume:/var/lib/swtpm-localca
    ports:
        - "9002:9002" # agent listen port
        - "8992:8992" # extra port, not present in vagrant example
    command:
      - /bin/bash
      - -c
      - |
        mkdir /tmp/tpmdir
        rm -rf /var/run/dbus
        mkdir /var/run/dbus
        dbus-daemon --system
        ls /etc/dbus-1/system.d/
        swtpm_setup --tpm2 \
            --tpmstate /tmp/tpmdir \
            --createek --decryption --create-ek-cert \
            --create-platform-cert \
            --display
        swtpm socket --tpm2 \
            --tpmstate dir=/tmp/tpmdir \
            --flags startup-clear \
            --ctrl type=tcp,port=2322 \
            --server type=tcp,port=2321 \
            --daemon
        tpm2-abrmd \
            --logger=stdout \
            --tcti=swtpm: \
            --allow-root \
            --flush-all &
        cd /rust-keylime && \
        /root/wait.sh /var/lib/keylime/cv_ca/client-cert.crt /bin/true && \
        sleep 2 && \
        /root/keylime_install2.sh && \
        tpm2_getekcertificate -o ECcert.bin && \
        openssl x509 -inform der -in ECcert.bin -out /var/lib/keylime/tpm_cert_store/swtpm.pem && \
        RUST_LOG=keylime_agent=trace cargo run --bin keylime_agent || \
        sleep 9999999999
volumes:
  keylime-volume:
  swtpm-volume:
